version: "3.8"
services:
  db:
    image: mysql:9.0.1
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: colegio
      MYSQL_USER: colegio
      MYSQL_PASSWORD: colegio
      MYSQL_ROOT_PASSWORD: test 
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default

  www:
    image: php:7.4-apache  
    ports: 
      - "80:80"
    volumes:
      - ./www/UD2/entregaTarea:/var/www/html
    links:
      - db
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    image: phpmyadmin:5.2.1
    links: 
      - db:db
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test 

volumes:
  persistent:
